import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('about:blank');
  await page.goto('chrome-error://chromewebdata/');
  await page.goto('https://kikuuboonline.com/');
  await page.goto('https://kikuuboonline.com/sign-in');
  await page.getByRole('link', { name: 'Sign Up' }).click();
  await page.locator('#name').click();
  await page.locator('#name').fill('Obeke');
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('vicent');
  await page.getByPlaceholder('Email Id').click();
  await page.getByPlaceholder('Email Id').fill('obekevicent@gmail.com');
  await page.getByPlaceholder('772000111').click();
  await page.getByPlaceholder('772000111').fill('786263898');
  await page.locator('#area').selectOption('Kalerwe');
  await page.getByPlaceholder('Atleast 6 character with an').click();
  await page.getByPlaceholder('Atleast 6 character with an').fill('CHes');
  await page.locator('.wd100 > span:nth-child(2)').first().click();
  await page.getByPlaceholder('Atleast 6 character with an').click();
  await page.getByPlaceholder('Atleast 6 character with an').fill('CHes1@kikonl');
  await page.getByPlaceholder('Confirm Password').click();
  await page.getByPlaceholder('Confirm Password').fill('CHes1@kikonl');
  await page.locator('#termsconf').check();
  await page.frameLocator('iframe[name="a-eh07zlljl04a"]').getByLabel('I\'m not a robot').click();
  await page.frameLocator('iframe[name="c-eh07zlljl04a"]').locator('.rc-imageselect-tile').first().click();
  await page.frameLocator('iframe[name="c-eh07zlljl04a"]').locator('tr:nth-child(2) > td').first().click();
  await page.frameLocator('iframe[name="c-eh07zlljl04a"]').locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.frameLocator('iframe[name="c-eh07zlljl04a"]').getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('#code3').click();
  await page.locator('#code1').click();
  await page.locator('#code1').fill('7');
  await page.locator('#code2').fill('0');
  await page.locator('#code3').fill('2');
  await page.locator('#code4').fill('9');
  await page.getByRole('button', { name: 'Verify & Proceed' }).click();
  await page.getByRole('button', { name: 'Yes, Verify email' }).click();
  await page.getByPlaceholder('OTP Code').fill('2065');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('link', { name: 'Obeke vicent' }).click();
  await page.getByRole('link', { name: 'Obeke vicent' }).click();
  await page.getByRole('link', { name: 'Obeke vicent' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
});